package com.processm.processminterpreter.pql.visitor

import PQLBaseVisitor
import PQLParser
import com.processm.processminterpreter.pql.CypherQuery
import org.slf4j.LoggerFactory

/**
 * ANTLR Visitor that translates PQL AST to Cypher queries
 *
 * This visitor walks through the Abstract Syntax Tree (AST) generated by ANTLR
 * and converts it into Neo4j Cypher query with parameters.
 */
class PQLToCypherVisitor(
    private val logId: String? = null,
) : PQLBaseVisitor<Any>() {

    private val logger = LoggerFactory.getLogger(PQLToCypherVisitor::class.java)
    private val parameters = mutableMapOf<String, Any>()
    private var paramCounter = 0
    private var currentNodeAlias: String = "event" // Default to event, will be set based on FROM clause

    /**
     * Entry point - visits the root query node
     */
    override fun visitQuery(ctx: PQLParser.QueryContext): CypherQuery {
        return visitSelectStatement(ctx.selectStatement()) as CypherQuery
    }

    /**
     * Main SELECT statement visitor
     * Extracts all query components and builds the final Cypher query
     */
    override fun visitSelectStatement(ctx: PQLParser.SelectStatementContext): CypherQuery {
        logger.debug("Visiting SELECT statement")

        // Extract query components from AST
        val distinct = ctx.distinct != null
        val selectClause = visit(ctx.selectList()) as String
        val fromClause = ctx.fromClause().text.lowercase()

        // Set current node alias based on FROM clause for WHERE clause translation
        currentNodeAlias = fromClause

        // Extract aliases from SELECT clause for ORDER BY handling
        val selectAliases = extractSelectAliases(ctx.selectList())

        val whereClause = ctx.whereClause()?.let { visitWhereClause(it) as String }
        val groupByClause = ctx.groupByClause()?.let { visitGroupByClause(it) as List<String> }
        val havingClause = ctx.havingClause()?.let { visitHavingClause(it) as String }
        val orderByClause = ctx.orderByClause()?.let { visitOrderByClause(it) as List<Pair<String, String>> }
        val limitClause = ctx.limitValue?.text

        logger.debug(
            "Parsed - DISTINCT: $distinct, SELECT: $selectClause, FROM: $fromClause, " +
                "WHERE: $whereClause, LIMIT: $limitClause",
        )

        // Build Cypher query based on FROM clause
        return when (fromClause) {
            "log" -> buildLogQuery(
                distinct,
                selectClause,
                whereClause,
                groupByClause,
                havingClause,
                orderByClause,
                limitClause,
                selectAliases,
            )
            "trace" -> buildTraceQuery(
                distinct,
                selectClause,
                whereClause,
                groupByClause,
                havingClause,
                orderByClause,
                limitClause,
                selectAliases,
            )
            "event" -> buildEventQuery(
                distinct,
                selectClause,
                whereClause,
                groupByClause,
                havingClause,
                orderByClause,
                limitClause,
                selectAliases,
            )
            else -> throw IllegalArgumentException("Unsupported FROM clause: $fromClause")
        }
    }

    /**
     * Visit SELECT * (all fields)
     */
    override fun visitSelectAll(ctx: PQLParser.SelectAllContext): String {
        return "*"
    }

    /**
     * Visit SELECT field list
     */
    override fun visitSelectItems(ctx: PQLParser.SelectItemsContext): String {
        return ctx.selectItem().joinToString(", ") { visit(it) as String }
    }

    /**
     * Visit SELECT item - aggregate function with optional alias
     */
    override fun visitSelectAggregate(ctx: PQLParser.SelectAggregateContext): String {
        val aggFunc = visitAggregateFunction(ctx.aggregateFunction()) as String
        val alias = ctx.alias?.let { getIdentifierText(it) }
        return if (alias != null) "$aggFunc AS $alias" else aggFunc
    }

    /**
     * Visit SELECT item - regular field with optional alias
     */
    override fun visitSelectField(ctx: PQLParser.SelectFieldContext): String {
        val field = getIdentifierText(ctx.field)
        val alias = ctx.alias?.let { getIdentifierText(it) }
        return if (alias != null) "$field AS $alias" else field
    }

    /**
     * Visit aggregate function (COUNT, AVG, SUM, MIN, MAX)
     */
    override fun visitAggregateFunction(ctx: PQLParser.AggregateFunctionContext): String {
        val funcName = when {
            ctx.COUNT() != null -> "count"
            ctx.AVG() != null -> "avg"
            ctx.SUM() != null -> "sum"
            ctx.MIN() != null -> "min"
            ctx.MAX() != null -> "max"
            else -> throw IllegalStateException("Unknown aggregate function")
        }

        val arg = if (ctx.STAR() != null) {
            "*"
        } else {
            ctx.identifier()?.let { getIdentifierText(it) } ?: throw IllegalStateException("Aggregate function requires argument")
        }

        return "$funcName($arg)"
    }

    /**
     * Visit WHERE clause
     */
    override fun visitWhereClause(ctx: PQLParser.WhereClauseContext): String {
        return visitOrCondition(ctx.orCondition()) as String
    }

    /**
     * Visit OR condition (lowest precedence)
     */
    override fun visitOrCondition(ctx: PQLParser.OrConditionContext): String {
        val conditions = ctx.andCondition().map { visitAndCondition(it) as String }
        return if (conditions.size > 1) {
            conditions.joinToString(" OR ")
        } else {
            conditions.first()
        }
    }

    /**
     * Visit AND condition (higher precedence than OR)
     */
    override fun visitAndCondition(ctx: PQLParser.AndConditionContext): String {
        val conditions = ctx.condition().map { visit(it) as String }
        return if (conditions.size > 1) {
            conditions.joinToString(" AND ")
        } else {
            conditions.first()
        }
    }

    /**
     * Visit IS NULL / IS NOT NULL condition
     */
    override fun visitIsNullCondition(ctx: PQLParser.IsNullConditionContext): String {
        val field = getIdentifierText(ctx.identifier())
        val translatedField = translateField(field, currentNodeAlias)
        val isNotNull = ctx.notNull != null
        return if (isNotNull) "$translatedField IS NOT NULL" else "$translatedField IS NULL"
    }

    /**
     * Visit BETWEEN condition
     */
    override fun visitBetweenCondition(ctx: PQLParser.BetweenConditionContext): String {
        val field = getIdentifierText(ctx.identifier())
        val translatedField = translateField(field, currentNodeAlias)
        val value1 = removeQuotes(ctx.value1.text)
        val value2 = removeQuotes(ctx.value2.text)
        val param1 = nextParamName()
        val param2 = nextParamName()
        parameters[param1] = value1
        parameters[param2] = value2
        return "$translatedField >= \$$param1 AND $translatedField <= \$$param2"
    }

    /**
     * Visit IN condition
     */
    override fun visitInCondition(ctx: PQLParser.InConditionContext): String {
        val field = getIdentifierText(ctx.identifier())
        val translatedField = translateField(field, currentNodeAlias)
        val values = visitStringList(ctx.stringList()) as List<String>
        val paramName = nextParamName()
        parameters[paramName] = values
        return "$translatedField IN \$$paramName"
    }

    /**
     * Visit comparison condition (=, <>, <, >, <=, >=, LIKE)
     */
    override fun visitComparisonCondition(ctx: PQLParser.ComparisonConditionContext): String {
        val field = getIdentifierText(ctx.identifier())
        val translatedField = translateField(field, currentNodeAlias)
        val operator = visitComparisonOp(ctx.comparisonOp()) as String
        val value: Any = if (ctx.value.type == PQLParser.STRING) {
            removeQuotes(ctx.value.text)
        } else {
            // NUMBER - convert to appropriate numeric type
            val text = ctx.value.text
            if (text.contains(".")) {
                text.toDouble()
            } else {
                text.toLongOrNull() ?: text.toInt()
            }
        }
        val paramName = nextParamName()
        parameters[paramName] = value
        return "$translatedField $operator \$$paramName"
    }

    /**
     * Visit parenthesized condition
     */
    override fun visitParenCondition(ctx: PQLParser.ParenConditionContext): String {
        return "(${visitOrCondition(ctx.orCondition()) as String})"
    }

    /**
     * Visit comparison operator
     */
    override fun visitComparisonOp(ctx: PQLParser.ComparisonOpContext): String {
        return when {
            ctx.EQ() != null -> "="
            ctx.NEQ() != null -> "<>"
            ctx.LT() != null -> "<"
            ctx.GT() != null -> ">"
            ctx.LTE() != null -> "<="
            ctx.GTE() != null -> ">="
            ctx.LIKE() != null -> "CONTAINS" // Convert LIKE to CONTAINS for Neo4j
            else -> throw IllegalStateException("Unknown comparison operator")
        }
    }

    /**
     * Visit GROUP BY clause
     */
    override fun visitGroupByClause(ctx: PQLParser.GroupByClauseContext): List<String> {
        return ctx.identifier().map { getIdentifierText(it) }
    }

    /**
     * Visit HAVING clause
     */
    override fun visitHavingClause(ctx: PQLParser.HavingClauseContext): String {
        val field = getIdentifierText(ctx.field)
        val translatedField = translateField(field, currentNodeAlias)
        val operator = visitComparisonOp(ctx.comparisonOp()) as String
        val valueExprCtx = ctx.valueExpr()
        val value: Any = if (valueExprCtx.NUMBER() != null) {
            // NUMBER - convert to the appropriate numeric type
            val valueText = valueExprCtx.NUMBER().text
            if (valueText.contains(".")) {
                valueText.toDouble()
            } else {
                valueText.toLongOrNull() ?: valueText.toInt()
            }
        } else {
            // identifier - keep as string (could be an alias or field reference)
            getIdentifierText(valueExprCtx.identifier())
        }
        val paramName = nextParamName()
        parameters[paramName] = value
        return "$translatedField $operator \$$paramName"
    }

    /**
     * Visit ORDER BY clause
     */
    override fun visitOrderByClause(ctx: PQLParser.OrderByClauseContext): List<Pair<String, String>> {
        return ctx.orderByItem().map { visitOrderByItem(it) as Pair<String, String> }
    }

    /**
     * Visit single ORDER BY item
     */
    override fun visitOrderByItem(ctx: PQLParser.OrderByItemContext): Pair<String, String> {
        val field = getIdentifierText(ctx.identifier())
        val direction = ctx.direction?.text?.uppercase() ?: "ASC"
        return field to direction
    }

    /**
     * Visit string list (for IN operator)
     */
    override fun visitStringList(ctx: PQLParser.StringListContext): List<String> {
        return ctx.STRING().map { removeQuotes(it.text) }
    }

    // =====================================
    // Helper methods for building Cypher
    // =====================================

    private fun buildLogQuery(
        distinct: Boolean,
        selectClause: String,
        whereClause: String?,
        groupByClause: List<String>?,
        havingClause: String?,
        orderByClause: List<Pair<String, String>>?,
        limitClause: String?,
        selectAliases: Set<String>,
    ): CypherQuery {
        val cypher = StringBuilder("MATCH (log:Log)")

        if (logId != null) {
            cypher.append(" WHERE log.logId = \$logId")
            parameters["logId"] = logId
        }

        if (whereClause != null) {
            cypher.append(if (logId != null) " AND " else " WHERE ")
            // whereClause is already translated by visitor methods
            cypher.append(whereClause)
        }

        // In Cypher, GROUP BY is implicit - fields not in aggregate functions are automatically grouped
        cypher.append(" RETURN ")
        if (distinct) cypher.append("DISTINCT ")
        cypher.append(translateSelectClause(selectClause, "log"))

        // HAVING is implemented using WITH clause in Cypher
        if (havingClause != null) {
            cypher.append(" WITH *")
            cypher.append(" WHERE ")
            cypher.append(havingClause)
        }

        if (orderByClause != null) {
            cypher.append(" ORDER BY ")
            cypher.append(
                orderByClause.joinToString(", ") {
                    val fieldName = if (selectAliases.contains(it.first)) it.first else translateField(it.first, "log")
                    "$fieldName ${it.second}"
                },
            )
        }

        if (limitClause != null) {
            cypher.append(" LIMIT $limitClause")
        }

        return CypherQuery(cypher.toString(), parameters)
    }

    private fun buildTraceQuery(
        distinct: Boolean,
        selectClause: String,
        whereClause: String?,
        groupByClause: List<String>?,
        havingClause: String?,
        orderByClause: List<Pair<String, String>>?,
        limitClause: String?,
        selectAliases: Set<String>,
    ): CypherQuery {
        val cypher = StringBuilder()

        if (logId != null) {
            cypher.append("MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)")
            parameters["logId"] = logId
        } else {
            cypher.append("MATCH (trace:Trace)")
        }

        if (whereClause != null) {
            cypher.append(" WHERE ")
            // whereClause is already translated by visitor methods
            cypher.append(whereClause)
        }

        // In Cypher, GROUP BY is implicit - fields not in aggregate functions are automatically grouped
        cypher.append(" RETURN ")
        if (distinct) cypher.append("DISTINCT ")
        cypher.append(translateSelectClause(selectClause, "trace"))

        // HAVING is implemented using WITH clause in Cypher
        if (havingClause != null) {
            cypher.append(" WITH *")
            cypher.append(" WHERE ")
            cypher.append(havingClause)
        }

        if (orderByClause != null) {
            cypher.append(" ORDER BY ")
            cypher.append(
                orderByClause.joinToString(", ") {
                    val fieldName = if (selectAliases.contains(it.first)) it.first else translateField(it.first, "trace")
                    "$fieldName ${it.second}"
                },
            )
        }

        if (limitClause != null) {
            cypher.append(" LIMIT $limitClause")
        }

        return CypherQuery(cypher.toString(), parameters)
    }

    private fun buildEventQuery(
        distinct: Boolean,
        selectClause: String,
        whereClause: String?,
        groupByClause: List<String>?,
        havingClause: String?,
        orderByClause: List<Pair<String, String>>?,
        limitClause: String?,
        selectAliases: Set<String>,
    ): CypherQuery {
        val cypher = StringBuilder()

        if (logId != null) {
            cypher.append("MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)")
            parameters["logId"] = logId
        } else {
            cypher.append("MATCH (event:Event)")
        }

        if (whereClause != null) {
            cypher.append(" WHERE ")
            // whereClause is already translated by visitor methods
            cypher.append(whereClause)
        }

        // In Cypher, GROUP BY is implicit - fields not in aggregate functions are automatically grouped
        cypher.append(" RETURN ")
        if (distinct) cypher.append("DISTINCT ")
        cypher.append(translateSelectClause(selectClause, "event"))

        // HAVING is implemented using WITH clause in Cypher
        if (havingClause != null) {
            cypher.append(" WITH *")
            cypher.append(" WHERE ")
            cypher.append(havingClause)
        }

        if (orderByClause != null) {
            cypher.append(" ORDER BY ")
            cypher.append(
                orderByClause.joinToString(", ") {
                    val fieldName = if (selectAliases.contains(it.first)) it.first else translateField(it.first, "event")
                    "$fieldName ${it.second}"
                },
            )
        }

        if (limitClause != null) {
            cypher.append(" LIMIT $limitClause")
        }

        return CypherQuery(cypher.toString(), parameters)
    }

    private fun translateSelectClause(selectClause: String, nodeAlias: String): String {
        return if (selectClause == "*") {
            "properties($nodeAlias) as $nodeAlias"
        } else {
            // Split by ", " carefully to handle aliases
            selectClause.split(Regex(",(?![^()]*\\))")).joinToString(", ") { item ->
                val trimmed = item.trim()
                val parts = trimmed.split(Regex("\\s+AS\\s+", RegexOption.IGNORE_CASE))
                if (parts.size == 2) {
                    "${translateFieldOrAggregate(parts[0].trim(), nodeAlias)} AS ${parts[1].trim()}"
                } else {
                    translateFieldOrAggregate(trimmed, nodeAlias)
                }
            }
        }
    }

    private fun translateFieldOrAggregate(expr: String, nodeAlias: String): String {
        return if (expr.contains("(")) {
            // Aggregate function
            val funcName = expr.substringBefore("(")
            val arg = expr.substringAfter("(").substringBefore(")")
            val translatedArg = if (arg == "*") "*" else translateField(arg, nodeAlias)
            "$funcName($translatedArg)"
        } else {
            // Regular field
            translateField(expr, nodeAlias)
        }
    }

    private fun translateFieldReferences(whereClause: String, nodeAlias: String): String {
        // Replace field names with nodeAlias['field'] or nodeAlias.field
        // Handle fields with namespace (e.g., org:group, concept:name)
        val fieldPattern = Regex("""\b([a-zA-Z_]\w*(?::[a-zA-Z_]\w*)?)\s*(=|<>|<|>|<=|>=|CONTAINS|IS|IN|AND|OR)""")
        return whereClause.replace(fieldPattern) { matchResult ->
            val field = matchResult.groupValues[1]
            val operator = matchResult.groupValues[2]

            // Check if it's a keyword (AND, OR) - don't translate
            if (field.uppercase() in listOf("AND", "OR", "IN", "IS")) {
                "$field $operator"
            } else {
                "${translateField(field, nodeAlias)} $operator"
            }
        }
    }

    private fun translateField(field: String, nodeAlias: String): String {
        if (nodeAlias == "event" && field.equals("traceId", ignoreCase = true)) {
            return "trace.traceId"
        }

        // Handle XES namespace properties (e.g., org:group, concept:name)
        // In Cypher, properties with colons need bracket notation
        return if (field.contains(":")) {
            "$nodeAlias['$field']"
        } else {
            when (field.lowercase()) {
                "id" -> "$nodeAlias.id"
                "name" -> "$nodeAlias.name"
                "activity" -> "$nodeAlias.activity"
                "timestamp" -> "$nodeAlias.timestamp"
                "resource" -> "$nodeAlias.resource"
                "caseid", "case_id" -> "$nodeAlias.caseId"
                else -> "$nodeAlias.$field"
            }
        }
    }

    private fun removeQuotes(str: String): String {
        return str.removeSurrounding("'").removeSurrounding("\"")
    }

    private fun nextParamName(): String = "param${paramCounter++}"

    /**
     * Extract text from identifier context
     * Handles both IDENTIFIER tokens and keyword tokens that can be used as identifiers
     */
    private fun getIdentifierText(ctx: PQLParser.IdentifierContext): String {
        return when {
            ctx.IDENTIFIER() != null -> ctx.IDENTIFIER().text
            ctx.COUNT() != null -> ctx.COUNT().text
            ctx.AVG() != null -> ctx.AVG().text
            ctx.SUM() != null -> ctx.SUM().text
            ctx.MIN() != null -> ctx.MIN().text
            ctx.MAX() != null -> ctx.MAX().text
            ctx.LOG() != null -> ctx.LOG().text
            ctx.TRACE() != null -> ctx.TRACE().text
            ctx.EVENT() != null -> ctx.EVENT().text
            ctx.ASC() != null -> ctx.ASC().text
            ctx.DESC() != null -> ctx.DESC().text
            else -> throw IllegalStateException("Unknown identifier type in context")
        }
    }

    /**
     * Extract aliases from SELECT clause
     * Returns a set of alias names defined in the SELECT clause
     */
    private fun extractSelectAliases(selectListCtx: PQLParser.SelectListContext): Set<String> {
        val aliases = mutableSetOf<String>()

        if (selectListCtx is PQLParser.SelectItemsContext) {
            selectListCtx.selectItem().forEach { selectItemCtx ->
                when (selectItemCtx) {
                    is PQLParser.SelectAggregateContext -> {
                        selectItemCtx.alias?.let { aliases.add(getIdentifierText(it)) }
                    }
                    is PQLParser.SelectFieldContext -> {
                        selectItemCtx.alias?.let { aliases.add(getIdentifierText(it)) }
                    }
                }
            }
        }

        return aliases
    }
}
