package com.processm.processminterpreter.pql.visitor

import QLParser
import QLParserBaseVisitor
import com.processm.processminterpreter.pql.CypherQuery
import org.slf4j.LoggerFactory

/**
 * ANTLR Visitor that translates ProcessM PQL AST to Neo4j Cypher queries
 *
 * This visitor walks through the Abstract Syntax Tree (AST) generated by ANTLR
 * from ProcessM's QL grammar and converts it into Neo4j Cypher queries with parameters.
 *
 * Key Features:
 * - SELECT queries (read_query)
 * - DELETE queries (delete_query)
 * - WHERE clauses with complex logic expressions
 * - Arithmetic expressions
 * - Scalar and aggregate functions
 * - SCOPE prefixes (log:/trace:/event:)
 * - GROUP BY, ORDER BY, LIMIT, OFFSET
 *
 * @param logId Optional log ID to filter results to a specific log
 */
class QLToCypherVisitor(
    private val logId: String? = null,
) : QLParserBaseVisitor<Any>() {

    private val logger = LoggerFactory.getLogger(QLToCypherVisitor::class.java)
    private val parameters = mutableMapOf<String, Any>()
    private var paramCounter = 0

    // Track current scope context for field resolution
    private var currentScope: Scope = Scope.EVENT
    private val scopeStack = mutableListOf<Scope>()

    enum class Scope {
        LOG, TRACE, EVENT
    }

    // ========================================
    // ENTRY POINT
    // ========================================

    /**
     * Entry point - visits the root query node
     * query: read_query EOF | delete_query EOF
     */
    override fun visitQuery(ctx: QLParser.QueryContext): CypherQuery {
        logger.debug("Visiting query: ${ctx.text}")

        return when {
            ctx.read_query() != null -> visitRead_query(ctx.read_query()) as CypherQuery
            ctx.delete_query() != null -> visitDelete_query(ctx.delete_query()) as CypherQuery
            else -> throw IllegalStateException("Unknown query type")
        }
    }

    // ========================================
    // READ QUERY (SELECT)
    // ========================================

    /**
     * read_query: select where? group_by? order_by? limit? offset?
     */
    override fun visitRead_query(ctx: QLParser.Read_queryContext): CypherQuery {
        logger.debug("Visiting read_query")

        // Determine scope from SELECT clause
        val selectCtx = ctx.select()
        determineScope(selectCtx)

        // Build components - dispatch to correct labeled alternative
        val selectClause = visit(selectCtx) as String
        val whereClause = ctx.where()?.let { visitWhere(it) as String }
        val groupByClause = ctx.group_by()?.let { visitGroup_by(it) as List<String> }
        val orderByClause = ctx.order_by()?.let { visitOrder_by(it) as List<OrderByItem> }
        val limitClause = ctx.limit()?.let { visitLimit(it) as List<Int> }
        val offsetClause = ctx.offset()?.let { visitOffset(it) as List<Int> }

        logger.debug("Parsed - Scope: $currentScope, SELECT: $selectClause, WHERE: $whereClause")

        return buildReadQuery(
            scope = currentScope,
            selectClause = selectClause,
            whereClause = whereClause,
            groupByClause = groupByClause,
            orderByClause = orderByClause,
            limitClause = limitClause,
            offsetClause = offsetClause,
        )
    }

    /**
     * Determine query scope from SELECT clause or context
     * Looks for SCOPE prefixes in column list
     */
    private fun determineScope(selectCtx: QLParser.SelectContext) {
        // Try to find scope from column_list
        val text = selectCtx.text.lowercase()

        currentScope = when {
            text.contains("event:") || text.contains("e:") -> Scope.EVENT
            text.contains("trace:") || text.contains("t:") -> Scope.TRACE
            text.contains("log:") || text.contains("l:") -> Scope.LOG
            else -> Scope.EVENT // Default to event
        }

        logger.debug("Determined scope: $currentScope")
    }

    /**
     * select_all_implicit
     */
    override fun visitSelect_all_implicit(ctx: QLParser.Select_all_implicitContext): String {
        return "*"
    }

    /**
     * select_all: SELECT '*'
     */
    override fun visitSelect_all(ctx: QLParser.Select_allContext): String {
        return "*"
    }

    /**
     * select_column_list: SELECT column_list
     */
    override fun visitSelect_column_list(ctx: QLParser.Select_column_listContext): String {
        // Process column_list - need to handle both labeled alternatives
        val columnListCtx = ctx.column_list()
        return when (columnListCtx) {
            is QLParser.Scoped_select_allContext -> visitScoped_select_all(columnListCtx) as String
            is QLParser.Column_list_arith_expr_rootContext -> visitColumn_list_arith_expr_root(columnListCtx) as String
            else -> throw IllegalStateException("Unknown column_list type")
        }
    }

    /**
     * scoped_select_all: SCOPE:*
     */
    override fun visitScoped_select_all(ctx: QLParser.Scoped_select_allContext): String {
        // SCOPE:* - return all fields for that scope
        return "*"
    }

    /**
     * column_list_arith_expr_root: arith_expr_root | arith_expr_root ',' column_list
     */
    override fun visitColumn_list_arith_expr_root(ctx: QLParser.Column_list_arith_expr_rootContext): String {
        // One or more expressions
        val expressions = mutableListOf<String>()
        var current: QLParser.Column_listContext? = ctx

        while (current != null) {
            if (current is QLParser.Column_list_arith_expr_rootContext) {
                val expr = visitArith_expr_root(current.arith_expr_root()) as String
                expressions.add(expr)
                current = current.column_list()
            } else if (current is QLParser.Scoped_select_allContext) {
                expressions.add("*")
                break
            } else {
                break
            }
        }

        return expressions.joinToString(", ")
    }

    override fun visitArith_expr_root(ctx: QLParser.Arith_expr_rootContext): String {
        return visitArith_expr(ctx.arith_expr()) as String
    }

    // ========================================
    // DELETE QUERY
    // ========================================

    /**
     * delete_query: delete where? order_by? limit? offset?
     */
    override fun visitDelete_query(ctx: QLParser.Delete_queryContext): CypherQuery {
        logger.debug("Visiting delete_query")

        val deleteCtx = ctx.delete()
        val scope = extractScopeFromDelete(deleteCtx)
        currentScope = scope

        val whereClause = ctx.where()?.let { visitWhere(it) as String }
        val orderByClause = ctx.order_by()?.let { visitOrder_by(it) as List<OrderByItem> }
        val limitClause = ctx.limit()?.let { visitLimit(it) as List<Int> }
        val offsetClause = ctx.offset()?.let { visitOffset(it) as List<Int> }

        return buildDeleteQuery(
            scope = scope,
            whereClause = whereClause,
            orderByClause = orderByClause,
            limitClause = limitClause,
            offsetClause = offsetClause,
        )
    }

    /**
     * delete: DELETE SCOPE?
     */
    private fun extractScopeFromDelete(ctx: QLParser.DeleteContext): Scope {
        val scopeText = ctx.SCOPE()?.text?.lowercase()
        return when (scopeText) {
            "log", "l" -> Scope.LOG
            "trace", "t" -> Scope.TRACE
            "event", "e" -> Scope.EVENT
            null -> Scope.EVENT // Default
            else -> Scope.EVENT
        }
    }

    // ========================================
    // WHERE CLAUSE
    // ========================================

    /**
     * where: WHERE logic_expr
     */
    override fun visitWhere(ctx: QLParser.WhereContext): String {
        return visitLogic_expr(ctx.logic_expr()) as String
    }

    /**
     * logic_expr: Complex logical expressions with proper precedence
     *
     * Precedence (high to low):
     * 1. Parentheses
     * 2. IN, NOT IN, MATCHES, LIKE
     * 3. Comparison operators
     * 4. NULL checks
     * 5. NOT
     * 6. AND
     * 7. OR
     */
    override fun visitLogic_expr(ctx: QLParser.Logic_exprContext): String {
        return when {
            // Parenthesized expression
            ctx.logic_expr().size == 1 && ctx.text.startsWith("(") -> {
                "(${visitLogic_expr(ctx.logic_expr(0)) as String})"
            }

            // IN / NOT IN
            ctx.OP_IN() != null || ctx.OP_NOT_IN() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0)) as String
                val operator = if (ctx.OP_IN() != null) "IN" else "NOT IN"
                val inList = visitIn_list(ctx.in_list()) as List<Any>
                val paramName = nextParamName()
                parameters[paramName] = inList
                "$leftExpr $operator \$$paramName"
            }

            // MATCHES (regex) / LIKE
            ctx.OP_MATCHES() != null || ctx.OP_LIKE() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0)) as String
                val pattern = removeQuotes(ctx.STRING().text)
                val paramName = nextParamName()

                if (ctx.OP_MATCHES() != null) {
                    // MATCHES -> Neo4j =~ (regex)
                    parameters[paramName] = pattern
                    "$leftExpr =~ \$$paramName"
                } else {
                    // LIKE -> Neo4j CONTAINS
                    parameters[paramName] = pattern
                    "$leftExpr CONTAINS \$$paramName"
                }
            }

            // Comparison operators
            ctx.OP_LT() != null || ctx.OP_LE() != null || ctx.OP_EQ() != null ||
                ctx.OP_NEQ() != null || ctx.OP_GT() != null || ctx.OP_GE() != null -> {
                val leftExpr = visitArith_expr(ctx.arith_expr(0)) as String
                val rightExpr = visitArith_expr(ctx.arith_expr(1)) as String
                val operator = when {
                    ctx.OP_LT() != null -> "<"
                    ctx.OP_LE() != null -> "<="
                    ctx.OP_EQ() != null -> "="
                    ctx.OP_NEQ() != null -> "<>"
                    ctx.OP_GT() != null -> ">"
                    ctx.OP_GE() != null -> ">="
                    else -> throw IllegalStateException("Unknown comparison operator")
                }
                "$leftExpr $operator $rightExpr"
            }

            // NULL checks
            ctx.OP_IS_NULL() != null || ctx.OP_IS_NOT_NULL() != null -> {
                val expr = visitArith_expr(ctx.arith_expr(0)) as String
                if (ctx.OP_IS_NULL() != null) {
                    "$expr IS NULL"
                } else {
                    "$expr IS NOT NULL"
                }
            }

            // NOT
            ctx.OP_NOT() != null -> {
                "NOT (${visitLogic_expr(ctx.logic_expr(0)) as String})"
            }

            // AND
            ctx.OP_AND() != null -> {
                val left = visitLogic_expr(ctx.logic_expr(0)) as String
                val right = visitLogic_expr(ctx.logic_expr(1)) as String
                "$left AND $right"
            }

            // OR
            ctx.OP_OR() != null -> {
                val left = visitLogic_expr(ctx.logic_expr(0)) as String
                val right = visitLogic_expr(ctx.logic_expr(1)) as String
                "$left OR $right"
            }

            else -> throw IllegalStateException("Unknown logic_expr type: ${ctx.text}")
        }
    }

    /**
     * in_list: '(' id_or_scalar_list ')'
     */
    override fun visitIn_list(ctx: QLParser.In_listContext): List<Any> {
        return visitId_or_scalar_list(ctx.id_or_scalar_list()) as List<Any>
    }

    /**
     * id_or_scalar_list: (ID | scalar) (',' (ID | scalar))*
     */
    override fun visitId_or_scalar_list(ctx: QLParser.Id_or_scalar_listContext): List<Any> {
        val values = mutableListOf<Any>()

        // Collect all IDs and scalars
        ctx.ID().forEach { values.add(it.text) }
        ctx.scalar().forEach { values.add(visitScalar(it)!!) }

        return values
    }

    // ========================================
    // ARITHMETIC EXPRESSIONS
    // ========================================

    /**
     * arith_expr: Arithmetic expressions with operator precedence
     *
     * Precedence (high to low):
     * 1. Parentheses
     * 2. Multiplication, Division
     * 3. Addition, Subtraction
     * 4. Functions, Identifiers, Scalars
     */
    override fun visitArith_expr(ctx: QLParser.Arith_exprContext): String {
        return when {
            // Parenthesized expression
            ctx.arith_expr().size == 1 && ctx.text.startsWith("(") -> {
                "(${visitArith_expr(ctx.arith_expr(0)) as String})"
            }

            // Multiplication or Division
            ctx.text.contains("*") || ctx.text.contains("/") -> {
                val left = visitArith_expr(ctx.arith_expr(0)) as String
                val right = visitArith_expr(ctx.arith_expr(1)) as String
                val operator = if (ctx.text.contains("*")) "*" else "/"
                "$left $operator $right"
            }

            // Addition or Subtraction
            ctx.text.contains("+") || (ctx.text.contains("-") && ctx.arith_expr().size > 1) -> {
                val left = visitArith_expr(ctx.arith_expr(0)) as String
                val right = visitArith_expr(ctx.arith_expr(1)) as String
                val operator = if (ctx.text.contains("+")) "+" else "-"
                "$left $operator $right"
            }

            // Function
            ctx.func() != null -> {
                visitFunc(ctx.func()) as String
            }

            // Identifier (field reference)
            ctx.ID() != null -> {
                translateFieldReference(ctx.ID().text)
            }

            // Scalar literal
            ctx.scalar() != null -> {
                val scalarValue = visitScalar(ctx.scalar())
                val paramName = nextParamName()
                parameters[paramName] = scalarValue!!
                "\$$paramName"
            }

            else -> throw IllegalStateException("Unknown arith_expr type: ${ctx.text}")
        }
    }

    /**
     * func: FUNC_SCALAR0 '()' | FUNC_SCALAR1 '(' arith_expr ')' | FUNC_AGGR '(' ID ')'
     */
    override fun visitFunc(ctx: QLParser.FuncContext): String {
        return when {
            // Zero-argument function (e.g., now())
            ctx.FUNC_SCALAR0() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_SCALAR0().text)
                translateScalarFunction0(funcName)
            }

            // Single-argument scalar function (e.g., year(timestamp))
            ctx.FUNC_SCALAR1() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_SCALAR1().text)
                val arg = visitArith_expr(ctx.arith_expr()) as String
                translateScalarFunction1(funcName, arg)
            }

            // Aggregate function (e.g., count(id))
            ctx.FUNC_AGGR() != null -> {
                val funcName = extractFunctionName(ctx.FUNC_AGGR().text)
                val arg = translateFieldReference(ctx.ID().text)
                translateAggregateFunction(funcName, arg)
            }

            else -> throw IllegalStateException("Unknown function type")
        }
    }

    private fun extractFunctionName(tokenText: String): String {
        // Remove scope prefix and opening parenthesis
        // e.g., "event:year(" -> "year"
        return tokenText.substringAfterLast(":").removeSuffix("(")
    }

    private fun translateScalarFunction0(funcName: String): String {
        return when (funcName.lowercase()) {
            "now" -> "datetime()" // Neo4j equivalent
            else -> throw IllegalArgumentException("Unsupported scalar function: $funcName")
        }
    }

    private fun translateScalarFunction1(funcName: String, arg: String): String {
        return when (funcName.lowercase()) {
            // Date/time extraction
            "year" -> "date($arg).year"
            "month" -> "date($arg).month"
            "day" -> "date($arg).day"
            "hour" -> "time($arg).hour"
            "minute" -> "time($arg).minute"
            "second" -> "time($arg).second"
            "millisecond" -> "time($arg).millisecond"
            "quarter" -> "((date($arg).month - 1) / 3) + 1" // Calculate quarter
            "dayofweek" -> "date($arg).dayOfWeek"

            // String manipulation
            "upper" -> "toUpper($arg)"
            "lower" -> "toLower($arg)"

            // Math
            "round" -> "round($arg)"

            // Date/time parsing
            "date" -> "date($arg)"
            "time" -> "time($arg)"

            else -> throw IllegalArgumentException("Unsupported scalar function: $funcName")
        }
    }

    private fun translateAggregateFunction(funcName: String, arg: String): String {
        return when (funcName.lowercase()) {
            "count" -> "count($arg)"
            "sum" -> "sum($arg)"
            "avg" -> "avg($arg)"
            "min" -> "min($arg)"
            "max" -> "max($arg)"
            else -> throw IllegalArgumentException("Unsupported aggregate function: $funcName")
        }
    }

    // ========================================
    // SCALARS & IDENTIFIERS
    // ========================================

    /**
     * scalar: STRING | NUMBER | BOOLEAN | DATETIME | UUID | NULL
     */
    override fun visitScalar(ctx: QLParser.ScalarContext): Any? {
        return when {
            ctx.STRING() != null -> {
                var value = removeQuotes(ctx.STRING().text)
                // Handle dates in string format: 'D2006-01-01' -> '2006-01-01'
                if (value.startsWith("D") && value.length >= 10 &&
                    value[1].isDigit() && value[5] == '-' && value[8] == '-'
                ) {
                    value = value.substring(1) // Remove 'D' prefix
                }
                value
            }
            ctx.NUMBER() != null -> {
                val text = ctx.NUMBER().text
                if (text.contains(".")) text.toDouble() else text.toLong()
            }
            ctx.BOOLEAN() != null -> ctx.BOOLEAN().text.toBoolean()
            ctx.DATETIME() != null -> {
                // Remove scope prefix and 'D' prefix from datetime
                // Examples: "D2006-01-01" -> "2006-01-01", "event:D2006-01-01T12:00:00" -> "2006-01-01T12:00:00"
                var datetime = ctx.DATETIME().text
                // Remove scope prefix if present (log:, trace:, event:, etc.)
                if (datetime.contains(":")) {
                    datetime = datetime.substringAfter(":")
                }
                // Remove 'D' prefix
                if (datetime.startsWith("D")) {
                    datetime = datetime.substring(1)
                }
                datetime
            }
            ctx.UUID() != null -> ctx.UUID().text
            ctx.NULL() != null -> null
            else -> throw IllegalStateException("Unknown scalar type")
        }
    }

    /**
     * Translate field reference with scope prefix
     *
     * Examples:
     * - event:activity -> event.activity
     * - e:activity -> event.activity
     * - activity -> event.activity (if current scope is event)
     * - trace:caseId -> trace.caseId
     * - ^trace:caseId -> trace.caseId (hoisting)
     */
    private fun translateFieldReference(fieldRef: String): String {
        // Remove brackets if present: [event:activity] -> event:activity
        val cleanRef = fieldRef.trim('[', ']')

        // Check if has scope prefix
        if (cleanRef.contains(":")) {
            val parts = cleanRef.split(":")
            val scopePart = parts[0].trimStart('^') // Remove hoisting markers
            val fieldPart = parts.drop(1).joinToString(":")

            val nodeLabel = when (scopePart.lowercase()) {
                "event", "e" -> "event"
                "trace", "t" -> "trace"
                "log", "l" -> "log"
                else -> scopeToNodeLabel(currentScope)
            }

            return translateField(fieldPart, nodeLabel)
        } else {
            // No scope prefix - use current scope
            return translateField(cleanRef, scopeToNodeLabel(currentScope))
        }
    }

    private fun scopeToNodeLabel(scope: Scope): String {
        return when (scope) {
            Scope.LOG -> "log"
            Scope.TRACE -> "trace"
            Scope.EVENT -> "event"
        }
    }

    private fun translateField(field: String, nodeLabel: String): String {
        // Handle special fields
        return when (field.lowercase()) {
            "id" -> "$nodeLabel.id"
            "name" -> "$nodeLabel.name"
            else -> {
                // Check if field contains : (nested namespace like concept:name)
                if (field.contains(":")) {
                    "$nodeLabel['$field']" // Bracket notation for namespaced fields
                } else {
                    "$nodeLabel.$field"
                }
            }
        }
    }

    // ========================================
    // OTHER CLAUSES
    // ========================================

    /**
     * group_by: GROUP_BY id_list
     */
    override fun visitGroup_by(ctx: QLParser.Group_byContext): List<String> {
        return visitId_list(ctx.id_list()) as List<String>
    }

    /**
     * id_list: ID (',' ID)*
     */
    override fun visitId_list(ctx: QLParser.Id_listContext): List<String> {
        return ctx.ID().map { translateFieldReference(it.text) }
    }

    /**
     * order_by: ORDER_BY column_list_with_order
     */
    override fun visitOrder_by(ctx: QLParser.Order_byContext): List<OrderByItem> {
        return visitColumn_list_with_order(ctx.column_list_with_order()) as List<OrderByItem>
    }

    /**
     * column_list_with_order: ordered_expression_root (',' ordered_expression_root)*
     */
    override fun visitColumn_list_with_order(ctx: QLParser.Column_list_with_orderContext): List<OrderByItem> {
        return ctx.ordered_expression_root().map {
            visitOrdered_expression_root(it) as OrderByItem
        }
    }

    /**
     * ordered_expression_root: arith_expr order_dir
     */
    override fun visitOrdered_expression_root(ctx: QLParser.Ordered_expression_rootContext): OrderByItem {
        val expr = visitArith_expr(ctx.arith_expr()) as String
        val direction = visitOrder_dir(ctx.order_dir()) as String
        return OrderByItem(expr, direction)
    }

    /**
     * order_dir: (empty) | ORDER_ASC | ORDER_DESC
     */
    override fun visitOrder_dir(ctx: QLParser.Order_dirContext): String {
        return when {
            ctx.ORDER_ASC() != null -> "ASC"
            ctx.ORDER_DESC() != null -> "DESC"
            else -> "ASC" // Default
        }
    }

    /**
     * limit: LIMIT limit_number (',' limit_number)*
     */
    override fun visitLimit(ctx: QLParser.LimitContext): List<Int> {
        return ctx.limit_number().map { visitLimit_number(it) as Int }
    }

    override fun visitLimit_number(ctx: QLParser.Limit_numberContext): Int {
        return ctx.NUMBER().text.toInt()
    }

    /**
     * offset: OFFSET offset_number (',' offset_number)*
     */
    override fun visitOffset(ctx: QLParser.OffsetContext): List<Int> {
        return ctx.offset_number().map { visitOffset_number(it) as Int }
    }

    override fun visitOffset_number(ctx: QLParser.Offset_numberContext): Int {
        return ctx.NUMBER().text.toInt()
    }

    // ========================================
    // CYPHER QUERY BUILDERS
    // ========================================

    data class OrderByItem(val expression: String, val direction: String)

    private fun buildReadQuery(
        scope: Scope,
        selectClause: String,
        whereClause: String?,
        groupByClause: List<String>?,
        orderByClause: List<OrderByItem>?,
        limitClause: List<Int>?,
        offsetClause: List<Int>?,
    ): CypherQuery {
        val cypher = StringBuilder()
        val nodeLabel = scopeToNodeLabel(scope)

        // Build MATCH clause based on scope and logId
        cypher.append(buildMatchClause(scope))

        // WHERE clause
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // RETURN clause
        cypher.append(" RETURN ")
        if (selectClause == "*") {
            cypher.append("properties($nodeLabel) as $nodeLabel")
        } else {
            cypher.append(selectClause)
        }

        // ORDER BY
        if (orderByClause != null && orderByClause.isNotEmpty()) {
            cypher.append(" ORDER BY ")
            cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
        }

        // SKIP (OFFSET)
        if (offsetClause != null && offsetClause.isNotEmpty()) {
            cypher.append(" SKIP ${offsetClause.first()}")
        }

        // LIMIT
        if (limitClause != null && limitClause.isNotEmpty()) {
            cypher.append(" LIMIT ${limitClause.first()}")
        }

        return CypherQuery(cypher.toString(), parameters.toMap())
    }

    private fun buildDeleteQuery(
        scope: Scope,
        whereClause: String?,
        orderByClause: List<OrderByItem>?,
        limitClause: List<Int>?,
        offsetClause: List<Int>?,
    ): CypherQuery {
        val cypher = StringBuilder()
        val nodeLabel = scopeToNodeLabel(scope)

        // Build MATCH clause
        cypher.append(buildMatchClause(scope))

        // WHERE clause
        if (whereClause != null || logId != null) {
            cypher.append(" WHERE ")
            val conditions = mutableListOf<String>()

            if (logId != null) {
                conditions.add("log.logId = \$logId")
                parameters["logId"] = logId
            }

            if (whereClause != null) {
                conditions.add(whereClause)
            }

            cypher.append(conditions.joinToString(" AND "))
        }

        // For DELETE with LIMIT/ORDER, we need to collect IDs first
        if (limitClause != null || offsetClause != null || orderByClause != null) {
            // Use subquery to get limited set
            cypher.append(" WITH $nodeLabel")

            if (orderByClause != null && orderByClause.isNotEmpty()) {
                cypher.append(" ORDER BY ")
                cypher.append(orderByClause.joinToString(", ") { "${it.expression} ${it.direction}" })
            }

            if (offsetClause != null && offsetClause.isNotEmpty()) {
                cypher.append(" SKIP ${offsetClause.first()}")
            }

            if (limitClause != null && limitClause.isNotEmpty()) {
                cypher.append(" LIMIT ${limitClause.first()}")
            }
        }

        // DELETE clause
        cypher.append(" DELETE $nodeLabel")

        return CypherQuery(cypher.toString(), parameters.toMap())
    }

    private fun buildMatchClause(scope: Scope): String {
        return when (scope) {
            Scope.LOG -> "MATCH (log:Log)"
            Scope.TRACE -> if (logId != null) {
                "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)"
            } else {
                "MATCH (trace:Trace)"
            }
            Scope.EVENT -> if (logId != null) {
                "MATCH (log:Log {logId: \$logId})-[:CONTAINS]->(trace:Trace)-[:HAS_EVENT]->(event:Event)"
            } else {
                "MATCH (event:Event)"
            }
        }
    }

    // ========================================
    // HELPERS
    // ========================================

    private fun removeQuotes(str: String): String {
        var result = str
        // Remove scope prefix if present
        if (result.contains(":")) {
            result = result.substringAfter(":")
        }
        // Remove quotes
        return result.trim().removeSurrounding("'").removeSurrounding("\"")
    }

    private fun nextParamName(): String = "param${paramCounter++}"
}
